### ISSUE TITLE
No Longer works in 4.18

### ISSUE THREAD

**Issue by TheJamsh** [ryanjon2040/UE4-Binary-Builder#1]
I've been using this tool since around ~4.15's release, and made a couple of modifications like adding PS4 / Xbone support etc.

It looks as though the program no longer works. You shouldn't be invoking AutomationTool.exe directly, but instead calling AutomationToolLauncher.exe which copies dependencies. If you don't do that, your build will fail.

See here: https://answers.unrealengine.com/questions/726010/418-will-not-build-from-source.html

**Comment by ryanjon2040** [comment]
Looks like you fixed the issue :).
