### ISSUE TITLE
document need to build automationtool and automationtoollauncher manually?

### ISSUE THREAD

**Issue by wchristian** [ryanjon2040/UE4-Binary-Builder#13]
Related to my experiences in #12: When those weren't built, binary builder failed in somewhat cryptic ways. It took me some poking around to figure out that they're built as part of UE4. Either i'm doing something wrong or it might be good to document that those need to be made manually first (and maybe anything else). Probably optimally those errors would be caught and replaced with instructive output?

**Comment by ryanjon2040** [comment]
Documentation added. Thanks to @tng2903
