### ISSUE TITLE
Issues with UE4.24

### ISSUE THREAD

**Issue by siegetech** [ryanjon2040/UE4-Binary-Builder#18]
With 4.24 i somehow no longer build successfully, 
i get lots of errors named : _**Memory.h(73): error C4834**_
Since i use the same procedure as always i tought this is a good place to start looking for answers.
Best

**Comment by ryanjon2040** [comment]
@siegetech This is not an issue with Binary Builder. 4.24 has issues using 14.24 compiler toolchain. You need to use 14.16 or 14.22 toolchain.
