### ISSUE TITLE
The path is not of a legal form

### ISSUE THREAD

**Issue by systemich** [ryanjon2040/UE4-Binary-Builder#19]
When zipping process & finding the files, i am getting "The path is not of a legal form"

![image_181731](https://user-images.githubusercontent.com/60100560/72796871-afb47900-3c72-11ea-9d69-46a507a67a7e.png)

I have entered "C:\Users\username\Documents" as the zip postbuild path. Because when i am entered "C:\Users\username\Documents\daily.zip" then the build cannot continue, have you tested the latest build zipping functionalities?.

**Comment by ryanjon2040** [comment]
@systemich Really sorry for this issue. It was a mistake after commit 55ae4cd4357d92824d7f87acd0e235a1ee26cda6 but @mathieudel fixed it and I've released a new version which you can get from here: https://github.com/ryanjon2040/UE4-Binary-Builder/releases/latest
