### ISSUE TITLE
Issue with `ShadowErrors`, `VS2017` and `Status Bar`

### ISSUE THREAD

**Issue by Bernardrouhi** [ryanjon2040/UE4-Binary-Builder#26]
I'm getting **Error that VS2017 must be installed**, while I do have **VS2017** and **VS2019**. Not sure why it's not detecting it.

This is the command line:
`BuildGraph -target="Make Installed Build Win64" -script="D:\Epic Games\UE_Source\UnrealEngine\Engine\Build\InstalledEngineBuild.xml" -set:WithDDC=false -set:SignExecutables=false -set:EmbedSrcSrvInfo=false -set:GameConfigurations=Development;Shipping -set:WithFullDebugInfo=false -set:HostPlatformEditorOnly=false -set:AnalyticsTypeOverride= -set:WithWin64=true -set:WithWin32=true -set:WithMac=false -set:WithAndroid=false -set:WithIOS=false -set:WithTVOS=false -set:WithLinux=false -set:WithLumin=false -set:WithLinuxAArch64=false -set:CompileDatasmithPlugins=false -set:VS2019=false -set:WithServer=false -set:WithClient=false -set:WithHoloLens=false`

I'm getting these errors :
- `SharedPCH.Core.ShadowErrors.cpp`
- `SharedPCH.CoreUObject.ShadowErrors.cpp`
- `SharedPCH.CoreUObject.RTTI.ShadowErrors.cpp`
- `SharedPCH.UnrealEd.NoOptimized.RTTI.ShadowErrors.NoUndef.cpp`
- `SharedPCH.Core.ShadowErrors.NoUndef.cpp`
- `SharedPCH.UnrealEd.NoOptimized.ShadowErrors.cpp`
- `SharedPCH.Engine.NoOptimized.ShadowErrors.cpp`
- `SharedPCH.Slate.ShadowErrors.cpp`
- `SharedPCH.UnrealEd.RTTI.ShadowErrors.cpp`
- `SharedPCH.UnrealEd.ShadowErrors.cpp`
- `SharedPCH.Engine.ShadowErrors.cpp`
Something with `ShadowErrors`, any idea why? 

fyi, I'm trying to build Chaos, so I edited the `BuildEnvironment = TargetBuildEnvironment.Shared;` to `BuildEnvironment = TargetBuildEnvironment.Unique;` and added `bCompileChaos = true;` and `bUseChaos = true;` to the `UE4Editor.Target.cs`. (That's since that's what unreal [**documentation**](https://docs.unrealengine.com/en-US/Engine/Chaos/ChaosDestruction/ChaosDestructionOverview/index.html) required.), is this causing the **ShadowErrors** errors?

...also I'm not sure what's going on at the status bar, probably need to give it some space or open a new window.
![image](https://user-images.githubusercontent.com/5335761/97277677-be6c3400-1873-11eb-8bde-c247f9bebbc8.png)

...and the last thing, regarding your documentation ("How to use").
"**Copy the built binary to the UE4 source folder prepared above.**"
after I built it, I copy the **release** folder in the **bin** folder and pasted it in the unreal source code directory, where **GenerateProjectFiles.bat** exists, am I doing it right?

**Comment by ryanjon2040** [comment]
@Bernardrouhi 

1: UE4 uses 2017 compiler by default so you will need to enable 2019 compiler option to use 2019 compiler. 

2: Those errors you mentioned are not errors actually. The program just detects them as errors because of some regex expression. 

3: I wasn't aware of the text overlapping. Thanks for pointing it out. I will fix it in next update.

**Comment by Bernardrouhi** [comment]
@ryanjon2040 

Okay, I tried building it again with VS2019, now I'm getting this
`AutomationException: Attempt to add file to temp storage manifest that does not exist (D:\Epic Games\UE_Source\UnrealEngine\cpp.hint)`

![image](https://user-images.githubusercontent.com/5335761/97332068-ff386d00-18b4-11eb-845a-7fb34b229daf.png)

Any idea what `cpp.hint` is? 

...also Is there anyways to build it faster? (3 hours+)

**Comment by ryanjon2040** [comment]
@Bernardrouhi 

That is a strange error. Never seen it before. I would advice posting it on the forums. `cpp.hint` is a [hint file](https://docs.microsoft.com/en-us/cpp/build/reference/hint-files?view=vs-2019).

The build time depends on the PC itself. Faster CPU + SSD should build faster.

**Comment by Bernardrouhi** [comment]
@ryanjon2040 
Thanks for the reply, alright, I'll post that on their forum.

**Comment by ryanjon2040** [comment]
@Bernardrouhi I'll close this issue for now since its not related to this application.

**Comment by Bernardrouhi** [comment]
Apparently, it's a bug in 4.25.4, and it's fixed in version 4.26 here is the snapshot of the git repo.
![image](https://user-images.githubusercontent.com/5335761/97495463-a1824e80-19a2-11eb-8cfb-d6af263ab2e3.png)

I remove line 520 and compile it again, and it did compile successfully. (thought to share that here)

**Comment by ryanjon2040** [comment]
Thank you so much for letting me know. I only tried on 4.25.3.
