### ISSUE TITLE
 trying to build 4.25.4, Exit Code 6/1 (no zip file created)

### ISSUE THREAD

**Issue by kusogaki77** [ryanjon2040/UE4-Binary-Builder#27]
I'm maintaining a [fork of the engine](https://github.com/kusogaki77/UnrealEngine), to which I just recently merged in the latest 4.25.4 hotfix.  It compiles w/o error.

Followed the steps on the usage instructions:
- Both AutomationTool and AutomationToolLauncher compiled w/o error
- I'm using the pre-built version of Binary Builder

Windows 10 64-bit Home is up-to-date.
I extracted Binary Builder to my Downloads folder, so it's on the C: drive w/ my OS. The UE4 source in question is on B:

First attempt at building gave me a PDBCOPY.EXE error, which canceled the build process. 
I have 3 different Windows SDKs installed.
10.1.17134.12
10.1.17763.132
10.1.18362.1
Modifying 10.1.18362.1 to install Debugging Tools for Windows fixed the PDBCOPY.EXE error.

Trying again, after 1.5 hours of building the binaries, it finishes - but with Exit Code 6, and the zip file is nowhere to be found.  
I initially specified the zip destination in a new folder on B:  Second attempt, I specified the zip destination in a new folder on the Desktop.

Most of the red text in the build log is on *ShadowErrors*.cpps  
![Unreal_Binary_Builder_2020-11-03_17-41-49](https://user-images.githubusercontent.com/9924826/97964668-7f525b80-1dfc-11eb-8eff-1af663241a6c.png)

Any hints as to what might be going wrong spent a couple hours trying to get find fixes, but no luck.

**Comment by ryanjon2040** [comment]
@kusogaki77 You have to disable **Mac** and **TvOS**. Apple doesn't allow building mac, iOS etc on other platforms.

**Comment by kusogaki77** [comment]
Thank you for the help. I guess I have to install the Linux SDK to build it for Linux.
I think most of the people using the fork I'm maintaining are running windows, so 
I disabled all platforms except for Windows x86 and X64.
Now I get a different error:
`Attempt to add file to temp storage manifest that does not exist (B:\UnrealEngine\cpp.hint)`

This happened after 4 hours of building this time, as opposed to 1.5h.  
![image](https://user-images.githubusercontent.com/9924826/98084487-37483d00-1ebf-11eb-89e0-f6c383e0b253.png)

Sorry for these questions.  This is the first time I've ever tried to build binaries.  Couldn't find any recent information on how to do it...

**Comment by ryanjon2040** [comment]
@kusogaki77 This is a bug in 4.25.4 which is fixed in 4.26 (found by @Bernardrouhi). You can find the solution in below link.

https://github.com/ryanjon2040/UE4-Binary-Builder/issues/26#issuecomment-718204352
