### ISSUE TITLE
Custom Branches?

### ISSUE THREAD

**Issue by Marius-Sheppard** [ryanjon2040/UE4-Binary-Builder#34]
Can we use this tool and not be bound only to these versions? (For example I'm trying to compile the master branch using this tool which is currently version 4.28.0)
![image](https://user-images.githubusercontent.com/49373200/119391590-33eb9600-bcd7-11eb-94f8-5224a2d73b7d.png)

**Comment by ryanjon2040** [comment]
Hi @Marius-Sheppard I've changed this behavior with this commit  04dbb9bfb3721c95a33c030bc22791bff607bae9
