### ISSUE TITLE
Issue building 4.23

### ISSUE THREAD

**Issue by CraigMason** [ryanjon2040/UE4-Binary-Builder#7]
Hello,

When building 4.23, I get an error related to HoloLens. I'm not sure why this is a stage:

Building inside of Visual Studio 2017 works without issue.

![image](https://user-images.githubusercontent.com/307066/65601082-532d9f80-df99-11e9-838b-fd3b6fe05c39.png)

**Comment by CraigMason** [comment]
Changing
`<Option Name="WithHoloLens" Restrict="true|false" DefaultValue="$(DefaultWithPlatform)" Description="Include the HoloLens target platform"/>`

to
`<Option Name="WithHoloLens" Restrict="true|false" DefaultValue="false" Description="Include the HoloLens target platform"/>`

Allows the build to complete.

I don't understand why `$(DefaultWithPlatform)` is not setting it to `false` when the log is clearly showing Host Only as true.

![image](https://user-images.githubusercontent.com/307066/65607294-3480d600-dfa4-11e9-81b6-dc24f63b97da.png)

Perhaps this is more an issue with `AutomationToolLauncher`

**Comment by CraigMason** [comment]
Correction:
`<Option Name="WithHoloLens" Restrict="true|false" DefaultValue="$(DefaultWithWindows)" Description="Include the HoloLens target platform"/>`

Is the original default. Perhaps we could add an option for 'WithHoloLens'?

Thank you

**Comment by ryanjon2040** [comment]
I've added support for HoloLens with this commit 01703735e1306befddcdd5fae086d8d23afe2187

You can get the new release here: https://github.com/ryanjon2040/UE4-Binary-Builder/releases/latest
