### ISSUE TITLE
Update to .Net Core

### ISSUE THREAD

**Issue by Ludea** [ryanjon2040/UE4-Binary-Builder#8]
Hello, can you  please update to
Net Core.
We can not build on Linux host for now. 
Update to .Net Core could resolve this
Or refactoring with electron framework?

**Comment by ryanjon2040** [comment]
Hi @Ludea I've not tried out .NET Core yet but I'll look into it and update this repo. 😄

**Comment by Ludea** [comment]
If you use electron I can help.

**Comment by Ludea** [comment]
Still no ETA to support .NET Core ?

It could be interesting to port into this and so, add support for Mac and Linux host

**Comment by ryanjon2040** [comment]
I've started porting this to .NET Core but progress is slow and I don't think it will support Mac and Linux since AFAIK .NET Core WPF apps does not support Mac and Linux.

**Comment by Ludea** [comment]
https://dotnet.microsoft.com/ 

> Supported on Windows, Linux, and macOS

**Comment by ryanjon2040** [comment]
@Ludea dotnet is cross platform but unfortunately dotnet WPF and WinForms are Windows only. Please check the below link.

https://github.com/dotnet/wpf/issues/48

**Comment by Ludea** [comment]
I see :(
Maybe consider switch to [Avalonia](https://github.com/AvaloniaUI/Avalonia)

**Comment by ryanjon2040** [comment]
@Ludea As of `v3.0` of Binary Builder I use `dotnet core` but still no support for Mac and Linux.

**Comment by Ludea** [comment]
I am planning to refactor your app, using a multiplaform framework

**Comment by ryanjon2040** [comment]
> I am planning to refactor your app, using a multiplaform framework

That's cool. May I know which framework @Ludea?

**Comment by Ludea** [comment]
I plan to use https://tauri.studio/en/
It's the same thing as electron, but based on rust

**Comment by Ludea** [comment]
Hi, I started something: https://github.com/Ludea/bupaku
It's the same thing as ue4builder but run on Win64, Macos and Linux.
