### ISSUE TITLE
HTML5 has been removed in 4.24

### ISSUE THREAD

**Issue by CraigMason** [ryanjon2040/UE4-Binary-Builder#9]
See https://github.com/EpicGames/UnrealEngine/commit/1e59611dbb7bb8d4d0092492410b516fb2c9db8e#diff-9e89386e56028900f1fe427f8ac167f6

**Comment by ryanjon2040** [comment]
Thanks @CraigMason I've added support for 4.24 and updated HTML5 with [this commit](https://github.com/ryanjon2040/UE4-Binary-Builder/commit/97c73d48f3b2de08d884f4aeee78a7dc884ee240).
